apiVersion: apps/v1
kind: Deployment # Defines how to deploy and manage the application
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # Creates 2 identical pods for redundancy
  selector:
    matchLabels:
      app: nginx # Links the deployment to pods with this label
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest # The Docker image to run
          ports:
            - containerPort: 80 # Port the container will use
          resources: # Resource limits and requests for the container
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
